services:
  db:
    environment:
      env_file: .env
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:z

  selenium:
    image: selenium/standalone-firefox:4.10.0-20230607
    ports:
      - 4444:4444
    restart: always
    shm_size: 2gb

  web:
    build:
      context: .
    command: >
      sh -c "sleep 20 &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - selenium
      - db
    env_file: .env
    image: chr-django-test
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

version: "3.9"

volumes:
  postgres_data:
