# Generated by Django 4.2.3 on 2023-07-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisprudence',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('tipo_causa', models.CharField(max_length=10)),
                ('rol', models.CharField(max_length=255)),
                ('caratula', models.CharField(max_length=255)),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('fecha_sentencia', models.CharField(max_length=10)),
                ('descriptores', models.CharField(max_length=255)),
                ('link_sentencia', models.CharField(max_length=255)),
                ('url_sentencia', models.CharField(max_length=255)),
                ('activo', models.BooleanField()),
                ('tribunal', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=10)),
                ('relacionada', models.CharField(blank=True, max_length=255)),
                ('visitas', models.IntegerField()),
            ],
        ),
    ]
