# Generated by Django 4.2.3 on 2023-07-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisprudence',
            name='caratula',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jurisprudence',
            name='descriptores',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jurisprudence',
            name='link_sentencia',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jurisprudence',
            name='nombre_proyecto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jurisprudence',
            name='relacionada',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='jurisprudence',
            name='rol',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jurisprudence',
            name='url_sentencia',
            field=models.CharField(max_length=500),
        ),
    ]
